apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: igw9d7hnw-python-gitops
  description: This is GitOps manifest for igw9d7hnw-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=igw9d7hnw-python
    backstage.io/kubernetes-id: igw9d7hnw-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: igw9d7hnw-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:igw9d7hnw-python
